name: Release All
on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 1
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install -g yarn
      - run: yarn install
      - run: yarn build
      - run: yarn test

      - name: Create '.npmrc' File 
        uses: filipstefansson/set-npm-token-action@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - id: set-version
        uses: actions/github-script@v4
        with:
          script: |
            const version = context.ref.replace(/^refs\/tags\//, '')
            core.setOutput('version', version)

      - name: Commit package.json
        run: |
          git config --global user.name "apicurio-ci[bot]"
          git config --global user.email "apicurio.ci@users.noreply.github.com"
          
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          yarn bump-version ${{ steps.set-version.outputs.version }}

          git add js/packages/*/package.json js/packages/*/package-lock.json

          git commit -m "chore(deps): bump packages to version ${{ steps.set-version.outputs.version }}"
          git push

      - name: Publish to npm
        run: ./scripts/releasePackages.sh